apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mjxy9/nginx:v0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80